# 工作流程的名稱（會顯示在 GitHub Actions 的畫面上）
name: Deploy to EC2 

# 當有人 push 到 main 分支時，就會觸發這個 workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 工作名稱
    name: Deploy Laravel Project to EC2
    # 指定 GitHub runner 執行環境（使用 Ubuntu）
    runs-on: ubuntu-latest

    steps:
      # 讓 runner 把 GitHub 上的程式碼 clone 下來到 runner 的本地目錄中。
      - name: Checkout repository
        uses: actions/checkout@v4

      # 建立 SSH 連線金鑰
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # SSH 登入 EC2 並執行部署指令
      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -x  

            cd ${{ secrets.EC2_PATH }}

            echo " 拉取最新程式碼..."
            git config --global --add safe.directory /var/www
            git pull origin main

            echo " 重建並啟動 Docker 容器..."
            docker-compose down
            docker-compose up -d --build

            echo " 設定 Git 安全目錄..."
            docker-compose exec -T app sh -c "git config --global --add safe.directory /var/www && echo OK"

            echo " 安裝 Composer 套件..."
            docker-compose exec -T app composer install --no-interaction --prefer-dist --optimize-autoloader

            echo " 設定 Swagger 權限與生成文件..."
            docker-compose exec -T app chown -R www-data:www-data storage/api-docs
            docker-compose exec -T app chmod -R 775 storage/api-docs
            docker-compose exec -T app php artisan l5-swagger:generate

            echo " 快取與設定清理..."
            docker-compose exec -T app php artisan config:clear
            docker-compose exec -T app php artisan route:clear
            docker-compose exec -T app php artisan config:cache
            docker-compose exec -T app php artisan route:cache

            echo " 執行 migrate..."
            docker-compose exec -T app php artisan migrate --force

            echo "部署完成！"
          EOF